# Generated by Django 4.2.7 on 2025-11-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="stripe_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserStripeAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_account_id", models.CharField(max_length=255, unique=True)),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("details_submitted", models.BooleanField(default=False)),
                ("requirements_due", models.JSONField(blank=True, default=list)),
                ("onboarding_url", models.URLField(blank=True)),
                ("onboarding_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user stripe account",
                "verbose_name_plural": "user stripe accounts",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="stripe_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="donations.userstripeaccount",
            ),
        ),
    ]
